quartz:
    scheduler: 
        cron: 
          increase: 0 0 0/1 * * ?
          update: 0 0 0/1 * * ?
config: 
    #######同步工具(可选datax和sqoop)
    sync_tool: datax
    #######linux hive相关信息
    remote_ssh_ip: 127.0.0.1
    remote_ssh_user: root
    remote_ssh_pwd: xcs@!#$DSFDF125
    
    #######datax JSON文件本地路径
    datax_job_dir: /root/datax/job
    
    #######linux服务器上datax_py路径
    datax_remote_path: /root/datax/bin/datax.py
    
    ######hadoop文件系统路径
    hadoop_dfs_path: /user/hive/warehouse
    
    #########hive连接配置
    hive_url: jdbc:hive2://127.0.0.1:10000/yinian
    hive_username: root
    hive_password: xcs@!#$DSFDF125
    hive_driver: org.apache.hive.jdbc.HiveDriver
    
    
    #########hive同步信息库连接配置
    hive_mysql_sync_url: jdbc:mysql://127.0.0.1:3306/hive_sync
    hive_mysql_sync_username: root
    hive_mysql_sync_password: EMRroot1234
    hive_mysql_sync_driver: com.mysql.jdbc.Driver
    
    #####业务库信息
    bi_mysql_url_part: jdbc:mysql://10.29.217.13:3306/
    bi_mysql_username: biuser
    bi_mysql_password: i0Gkah5;uG
    bi_mysql_driver: com.mysql.jdbc.Driver
    bi_mysql_schema: yinian
    
    ######mysql内网地址
    bi_mysql_url_inner_ip: 10.29.217.13
    
    ######邮件信息
    from_mail_account: 1462350571@qq.com
    from_mail_pwd: 57v42s
    from_mail_smtp_host: smtp.qq.com
    to_mail_account: 635891879@qq.com
    from_personal: 大数据同步平台
    to_personal: 尊敬的工程师
    
